name: Postman Tests

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
  
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16
  
        - name: Install Newman
          run: npm install -g newman
  
        - name: Install JSON Server
          run: npm install -g json-server

        # Create a copy of the original db.json
        - name: Create db.json Copy
          run: cp db.json dbcopy.json
  
        # Start JSON Server with the copy of db.json
        - name: Start JSON Server
          run: npx json-server --watch dbcopy.json &

        # Sleep for 5 seconds to allow JSON Server to start
        - name: Wait for JSON Server
          run: sleep 5
  
        # Run Postman Tests and generate a report
        - name: Run Postman Tests
          run: newman run postman-tests/Users.postman_collection.json -e postman-tests/api-test-json-server.postman_environment.json --reporters cli,junit --reporter-junit-export postman-report.xml

        # Upload the Postman test report as an artifact
        - name: Upload Test Report
          uses: actions/upload-artifact@v2
          with:
           name: postman-test-report
           path: postman-report.xml
  